// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9r8cmLF6L6loNpT3TOUw5dp0V40AVxJ4',
    appId: '1:717070860607:web:e5099d2cd5134c7bf2938a',
    messagingSenderId: '717070860607',
    projectId: 'fir-flutter-codelab-62405',
    authDomain: 'fir-flutter-codelab-62405.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-62405.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsYqrBOm-g87Vwymr9N-5mrbXSNYzDF8',
    appId: '1:717070860607:android:12d31b56b1fbc745f2938a',
    messagingSenderId: '717070860607',
    projectId: 'fir-flutter-codelab-62405',
    storageBucket: 'fir-flutter-codelab-62405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEeHli2RjLrvyn_MAIn8P3pQ_K5UpRsuc',
    appId: '1:717070860607:ios:a9e4682eaefe623bf2938a',
    messagingSenderId: '717070860607',
    projectId: 'fir-flutter-codelab-62405',
    storageBucket: 'fir-flutter-codelab-62405.appspot.com',
    iosClientId: '717070860607-4ip36pdbfda4412vqbuocsaoej54sno4.apps.googleusercontent.com',
    iosBundleId: 'com.example.theChurche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEeHli2RjLrvyn_MAIn8P3pQ_K5UpRsuc',
    appId: '1:717070860607:ios:ce1260f866925b42f2938a',
    messagingSenderId: '717070860607',
    projectId: 'fir-flutter-codelab-62405',
    storageBucket: 'fir-flutter-codelab-62405.appspot.com',
    iosClientId: '717070860607-a9832nbp2m0j5gc1d325dmqos7gnav76.apps.googleusercontent.com',
    iosBundleId: 'com.example.theChurche.RunnerTests',
  );
}
